name: updatecli/install

description: |
  This is an opinionated GitHub Action to install the updatecli

inputs:
  version:
    description: "Install a specific version of oblt-cli. If both `version` and `version-file` are provided, `version` will be used."
    required: false
  version-file:
    description: "The file to read the version from. E.g. `.oblt-cli-version` or `.tool-versions` (asdf-vm)."
    required: false

runs:
  using: composite
  steps:
    - name: Check inputs and set version
      id: set-version
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs')
          const path = require('path')

          const version = core.getInput('version')
          const versionFile = core.getInput('version-file')
          const defaultVersionPath = path.join(process.env.GITHUB_ACTION_PATH, '.default-updatecli-version')

          if (!version && !versionFile) {
            if (fs.existsSync(defaultVersionPath)) {
              const newVersion = fs.readFileSync(defaultVersionPath, 'utf8').trim()
              core.setOutput('version', newVersion)
            } else {
              core.setFailed('Default version file not found.')
            }
          } else {
            core.setOutput('version', version)
            core.setOutput('version_file', versionFile)
          }

    - name: Install Updatecli in the runner
      uses: updatecli/updatecli-action@cb631ef5547ed05db3db64bb2ad42a6cc36e3097 # v2.71.0
      with:
        version: ${{ steps.set-version.outputs.version }}
        version-file: ${{ steps.set-version.outputs.version_file }}
