name: updatecli/install

description: |
  This is an opinionated GitHub Action to install the updatecli

inputs:
  version:
    description: "Install a specific version of oblt-cli. If both `version` and `version-file` are provided, `version` will be used."
    required: false
  version-file:
    description: "The file to read the version from. E.g. `.oblt-cli-version` or `.tool-versions` (asdf-vm)."
    required: false

runs:
  using: composite
  steps:
    - name: Install Updatecli in the runner
      uses: updatecli/updatecli-action@cb631ef5547ed05db3db64bb2ad42a6cc36e3097 # v2.71.0
      with:
        version: ${{ inputs.version }}
        version-file: ${{ inputs.version-file }}
