name: oblt-cli/flags

description: |
  Generate flags for oblt-cli.

inputs:
  cluster-name-prefix:
    description: 'The cluster name prefix'
    required: false
  cluster-name-suffix:
    description: 'The cluster name suffix'
    required: false
  dry-run:
    description: 'Whether to dryRun'
    default: false
    required: false

outputs:
    result:
      description: 'The flags to be passed to oblt-cli'
      value: ${{ steps.flags.outputs.result }}

runs:
  using: composite
  steps:
    - name: Generate dry-run flag
      id: flags
      uses: actions/github-script@v7
      env:
        DRY_RUN: ${{ inputs.dry-run }}
        CLUSTER_NAME_PREFIX: ${{ inputs.cluster-name-prefix }}
        CLUSTER_NAME_SUFFIX: ${{ inputs.cluster-name-suffix }}
      with:
        result-encoding: string
        script: |
          const flags = []
          if (process.env.DRY_RUN === true) {
              core.setOutput('DRY_RUN', '--dry-run')
          }
          if (process.env.CLUSTER_NAME_PREFIX) {
              flags.push(`--cluster-name-prefix='${process.env.CLUSTER_NAME_PREFIX}'`)
          }
          if (process.env.CLUSTER_NAME_SUFFIX) {
              flags.push(`--cluster-name-suffix='${process.env.CLUSTER_NAME_SUFFIX}'`)
          }
          return flags.join(' ')
