name: test-slack-send

on:
  pull_request:
    branches:
      - main
      - test/send-with-multiline
    paths:
      - '.github/workflows/test-slack-send.yml'
      - 'slack/send/**'
  push:
    branches:
      - main
      - test/send-with-multiline
    paths:
      - '.github/workflows/test-slack-send.yml'
      - 'slack/send/**'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./slack/send
        id: slack-send
        env:
          area_label: "SDH"
          notification_urgency: "High"
          tests: '\n&*()'
        with:
          bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel-id: "#observablt-bots"
          message: |
            :wave: Hello, @robots-ci! A new SDH issue has been cut for `${{ env.area_label }}`:
            You are being "notified${{env.tests}}%" as a fallback mechanism, as `${{ env.area_label }}` does not match any of my configured area labels.

            *${{ env.notification_urgency }} <${{ github.event.issue.html_url }}|#${{ github.event.issue.number }} - ${{ github.event.issue.title }}>*
