name: test-updatecli-install

on:
  merge_group: ~
  workflow_dispatch: ~
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/test-updatecli-install.yml'
      - 'updatecli/install/**'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/test-updatecli-install.yml'
      - 'updatecli/install/**'

permissions:
  contents: read

jobs:
  test:
    needs:
      - default
      - version
      - version-file
    runs-on: ubuntu-latest
    steps:
      - id: check
        uses: elastic/oblt-actions/check-dependent-jobs@v1
        with:
          jobs: ${{ toJSON(needs) }}
      - run: ${{ steps.check.outputs.is-success }}

  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./updatecli/install
      - name: Verify updatecli version
        run: |
          version=$(cat updatecli/install/.default-updatecli-version)
          [[ "$(updatecli version 2>&1)" == *"${version}"* ]]

  version:
    runs-on: ubuntu-latest
    env:
      VERSION: "0.86.0"
    steps:
      - uses: actions/checkout@v4
      - uses: ./updatecli/install
        with:
          version: "v${{ env.VERSION }}"
      - name: Verify updatecli version
        run: |
          currentVersion=$(updatecli version 2>&1)
          [[ "${currentVersion}" == *"${VERSION}"* ]]

  version-file:
    runs-on: ubuntu-latest
    env:
      VERSION: "0.87.0"
    steps:
      - uses: actions/checkout@v4
      - name: Setup version file
        run: |
          echo "v${VERSION}" > .tools-version
      - uses: ./updatecli/install
        with:
          version-file: .tools-version
      - name: Verify updatecli version
        run: |
          currentVersion=$(updatecli version 2>&1)
          [[ "${currentVersion}" == *"${VERSION}"* ]]
